### ISSUE TITLE
Szerokość logo HS - ucięta litera o.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/define-normalnosc#10]
Opis:
Na stronie głównej i w sekcji "Partnerzy" w logo HS ucięta litera o (szerokość logo). Miejsca zaznaczone na żółto za screenach
![3  Szerokość logo](https://user-images.githubusercontent.com/92811043/157313709-8c09231d-9b90-47dd-be92-0eeb3fd1a3b5.PNG)
![7  Logo HS dół](https://user-images.githubusercontent.com/92811043/157313762-07a689db-247a-4323-9a2f-621839cc9f13.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by maknetaRo** [comment]
Zmieniłam na razie tylko w index.html z svg na plik .png. Czy teraz jest lepiej? Jeśli już nie ucina tej literki, to wszędzie pozmieniam. (Tzn. na podstronach prelegentów)

**Comment by tgbdc7** [comment]
to dolne logo jest okey. Górne trzeba poprawić. 

![image](https://user-images.githubusercontent.com/27868010/158119365-8dd293f0-2e7d-41e2-81f9-cfc12c233c7c.png)

**Comment by maknetaRo** [comment]
Dolne czyli w stopce.  Górne czyli tuż nad przyciskiem Zapisz się?

**Comment by AgnieszkaS4** [comment]
Tak, dole w stopce jest ok. Górne nad przyciskiem "Zapisz się" jest ucięte. 

![HS logo góra](https://user-images.githubusercontent.com/92811043/158227932-9c7fbd72-9a6d-4c9f-9f21-42af6938e5a4.PNG)
.

**Comment by maknetaRo** [comment]
zmieniłam wszędzie z svg na plik png, proszę sprawdzić i dać znać czy tak lepiej.

**Comment by AgnieszkaS4** [comment]
Tak. Teraz wygląda super. Nic nie jest ucięte.
