### ISSUE TITLE
Prelegenci - Szymon Moliński - literówka w opisie prelegenta.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/define-normalnosc#16]
Opis: Prelegenci - u Szymona Molińskiego w opisie profilu znajduje się literówka w zdaniu
![2  Szymon literówka](https://user-images.githubusercontent.com/92811043/158239341-0511f0f5-a8d0-4098-a603-7a44f833baeb.PNG)
.

Środowisko:
Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by maknetaRo** [comment]
poprawione

**Comment by AgnieszkaS4** [comment]
Wszystko ok.
