### ISSUE TITLE
Prelegenci - Michał Szpor- literówki w opisie profilu.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/define-normalnosc#17]
Opis: Prelegenci _ Michał Szpor - literówki w opisie profilu
1. Literówka w słowie MindMapingu - powinno być zapisane Mind Mappingu
![1  Literówka](https://user-images.githubusercontent.com/92811043/158242639-b231614f-2b99-4f0b-ab67-760b9e043966.PNG)

2. Literówka w nazwie firmy Carefour - powinno być zapisane Carrefour
![2  Nazwa literówka Carrefour](https://user-images.githubusercontent.com/92811043/158242847-4df57280-e6af-4783-82fc-9ea2fd3946a2.PNG)

3. Rozdzielenie nazw firm C.Hartwig Gdynia S.A. Aperam. Po S.A. powinien być przecinek, aby zobrazować, że firma Aperam to kolejna wymieniona oddzielna/ inna firma.
![3  Firmy nazwy](https://user-images.githubusercontent.com/92811043/158243375-4f74f271-0050-4516-b0b5-35c9d2d2edc7.PNG)

**Comment by maknetaRo** [comment]
poprawione

**Comment by AgnieszkaS4** [comment]
Wszystko ok.
