### ISSUE TITLE
Prelegenci - Ola Rodzeiwcz brak konsekwencji w zapisie " trenerka wiodąca".

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/define-normalnosc#18]
Opis: Prelegenci - Ola Rodzeiwcz w opisie profilu brak konsekwencji w zapisie nazwy stanowiska " trenerka wiodąca". W jednym zdaniu zapis z dużej litery, w kolejnym zdaniu zapis z małej litery.
![1  Ola zapis](https://user-images.githubusercontent.com/92811043/158247895-7e576c79-8f2a-4c02-aafc-7beeb8fc22c6.PNG)

Środowisko:
Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by maknetaRo** [comment]
Napisałam dużą literą.

**Comment by AgnieszkaS4** [comment]
Ok.
