### ISSUE TITLE
Prelegenci - Ola Rodzeiwcz brak przecinka rozdzielającego stowarzyszenie i kolejną funkcję.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/define-normalnosc#19]
Opis: Prelegenci - Ola Rodzeiwcz w opisie profilu brakuje przecinka w zdaniu "Trenerka Wiodąca w Stowarzyszeniu FRRPW Członkini Zarządu Fundacji Hybrydowa Szkoła". Po Stowarzyszeniu FRRPW powinien znajdować się przecinek, aby oddzielić wymienioną dalej funkcję członkini zarządu.

![2  Ola brak przecinka](https://user-images.githubusercontent.com/92811043/158248661-ab5de539-fc73-4357-8f7f-89a9117366f0.PNG)

Środowisko:
Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by maknetaRo** [comment]
zrobione

**Comment by AgnieszkaS4** [comment]
Ok.
